name: Build and Release Deno Binary

on:
  push:
    tags:
      - 'v*' # Trigger only for version tags
permissions:
  contents: write

jobs:
  build:
    name: Build Deno Binary
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Deno environment
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Compile the Deno app
      - name: Compile Deno Binary
        run: |
          deno compile --output ./cr-linux ./src/index.ts
          ls -lh ./cr-linux # Confirm binary creation

      # Upload the binary to GitHub Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cr-linux
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authorization
